import { Screen, type RGB } from '../term.ts';
export const P = { bg:[0,0,0], fg:[199,205,217], white:[235,239,246], dim:[113,123,143], line:[38,45,59], blue:[125,168,239], green:[101,197,146], amber:[218,177,101], red:[232,119,129], select:[12,23,40] } satisfies Record<string, RGB>;
export function safe(value: unknown): string {
  return String(value ?? '').replace(/\x1b\][\s\S]*?(?:\x07|\x1b\\|$)/g,'').replace(/\x1b[P_X^][\s\S]*?(?:\x1b\\|$)/g,'').replace(/(?:\x1b\[|\u009b)[0-?]*[ -/]*[@-~]/g,'').replace(/\x1b[@-_]/g,'').replace(/[\p{Cc}\p{Cf}\p{M}]/gu,'').replace(/[\u1100-\u115f\u2329\u232a\u2e80-\ua4cf\uac00-\ud7a3\uf900-\ufaff\ufe10-\ufe19\ufe30-\ufe6f\uff00-\uff60\uffe0-\uffe6]|[\u{1f000}-\u{1ffff}]|[\u{20000}-\u{3ffff}]/gu,'?');
}
export function clip(value: unknown, w: number): string { const a=[...safe(value)]; return a.length>w ? a.slice(0,Math.max(0,w-1)).join('')+(w>0?'…':'') : a.join(''); }
export function txt(s:Screen,x:number,y:number,value:unknown,w=s.w-x,fg:RGB=P.fg,bold=false) { s.put(x,y,clip(value,Math.max(0,w)),{fg,bold}); }
export function wrap(value:unknown,w:number):string[] {
  if(w<1)return []; const out:string[]=[];
  for(const paragraph of String(value??'').split('\n')) { let row=''; for(const word of safe(paragraph).split(/\s+/)) { if(!word)continue; if(row&&row.length+word.length+1>w){out.push(row);row='';} let rest=word; while(rest.length>w){if(row){out.push(row);row='';}out.push(rest.slice(0,w));rest=rest.slice(w);} if(rest)row+=(row?' ':'')+rest; } out.push(row); }
  return out;
}
export function para(s:Screen,x:number,y:number,w:number,h:number,value:unknown,fg:RGB=P.fg,scroll=0) { const rows=wrap(value,w),start=Math.min(Math.max(0,scroll),Math.max(0,rows.length-h));rows.slice(start,start+Math.max(0,h)).forEach((l,i)=>txt(s,x,y+i,l,w,fg)); }
export function label(s:Screen,x:number,y:number,w:number,name:string,right='') { txt(s,x,y,'─'.repeat(Math.max(0,w)),w,P.line); txt(s,x,y,name+' ',w,P.dim,true); if(right)txt(s,x+w-Math.min(w,right.length),y,right,w,P.dim); }
export function box(s:Screen,x:number,y:number,w:number,h:number,color:RGB=P.line,bg:RGB=P.bg) { if(w<2||h<2)return; s.fill(x,y,w,h,' ',{bg}); txt(s,x,y,'╭'+'─'.repeat(w-2)+'╮',w,color); txt(s,x,y+h-1,'╰'+'─'.repeat(w-2)+'╯',w,color); for(let i=1;i<h-1;i++){txt(s,x,y+i,'│',1,color);txt(s,x+w-1,y+i,'│',1,color);} }
export const pct=(n:number|null|undefined)=>n!=null&&Number.isFinite(n)?Math.max(0,Math.min(100,n)):null;
export const statusColor=(status:string):RGB=>status==='ok'||status==='done'||status==='ACT'?P.green:status==='blocked'||status==='HOLD'?P.red:status==='waiting'||status==='WAIT'?P.amber:status==='active'?P.blue:P.dim;
export const statusWord=(status:string)=>({ok:'On track',blocked:'Blocked',waiting:'Waiting',unknown:'Unknown'}[status]??status);
export function bar(s:Screen,x:number,y:number,w:number,value:number|null,color:RGB) { const n=pct(value); txt(s,x,y,'━'.repeat(Math.max(0,w)),w,P.line); if(n!==null)txt(s,x,y,'━'.repeat(Math.round(w*n/100)),w,color); }
const FONT:Record<string,string[]>={ '0':['###','#.#','#.#','#.#','###'],'1':['.#.','##.','.#.','.#.','###'],'2':['###','..#','###','#..','###'],'3':['###','..#','.##','..#','###'],'4':['#.#','#.#','###','..#','..#'],'5':['###','#..','###','..#','###'],'6':['###','#..','###','#.#','###'],'7':['###','..#','.#.','.#.','.#.'],'8':['###','#.#','###','#.#','###'],'9':['###','#.#','###','..#','###'],A:['.#.','#.#','###','#.#','#.#'],B:['##.','#.#','##.','#.#','##.'],C:['.##','#..','#..','#..','.##'],D:['##.','#.#','#.#','#.#','##.'],E:['###','#..','##.','#..','###'],F:['###','#..','##.','#..','#..'],G:['.##','#..','#.#','#.#','.##'],H:['#.#','#.#','###','#.#','#.#'],I:['###','.#.','.#.','.#.','###'],J:['..#','..#','..#','#.#','.#.'],K:['#.#','#.#','##.','#.#','#.#'],L:['#..','#..','#..','#..','###'],M:['#.#','###','###','#.#','#.#'],N:['##.','#.#','#.#','#.#','#.#'],O:['.#.','#.#','#.#','#.#','.#.'],P:['##.','#.#','##.','#..','#..'],Q:['.#.','#.#','#.#','##.','.##'],R:['##.','#.#','##.','#.#','#.#'],S:['.##','#..','.#.','..#','##.'],T:['###','.#.','.#.','.#.','.#.'],U:['#.#','#.#','#.#','#.#','###'],V:['#.#','#.#','#.#','#.#','.#.'],W:['#.#','#.#','#.#','###','#.#'],X:['#.#','#.#','.#.','#.#','#.#'],Y:['#.#','#.#','.#.','.#.','.#.'],Z:['###','..#','.#.','#..','###'],'-':['...','...','###','...','...'],'#':['#.#','###','#.#','###','#.#'],'.':['...','...','...','...','.#.']};
export function big(s:Screen,x:number,y:number,value:string,color:RGB=P.white,max=s.w-x) { const chars=[...safe(value).toUpperCase()].slice(0,Math.floor((max+1)/4)); chars.forEach((ch,i)=>{const g=FONT[ch];if(!g)return;for(let col=0;col<3;col++)for(let row=0;row<3;row++){const top=g[row*2]?.[col]==='#',bottom=g[row*2+1]?.[col]==='#';if(top||bottom)s.put(x+i*4+col,y+row,top?'▀':'▄',{fg:color,...(top&&bottom?{bg:color}:{})});}});return chars.length*4-1; }
const bits=[[1,8],[2,16],[4,32],[64,128]];
export function ring(s:Screen,x:number,y:number,value:number|null,color:RGB,w=16,h=8) { const n=pct(value);for(let cy=0;cy<h;cy++)for(let cx=0;cx<w;cx++){let mask=0,active=0;for(let dy=0;dy<4;dy++)for(let dx=0;dx<2;dx++){const px=(cx*2+dx-(w*2-1)/2)/(w-1),py=(cy*4+dy-(h*4-1)/2)/(h*2-1);const r=Math.hypot(px,py);if(r>.83&&r<1.03){const bit=bits[dy][dx];mask|=bit;const angle=(Math.atan2(px,-py)+Math.PI*2)%(Math.PI*2);if(n!==null&&angle<=n/100*Math.PI*2)active|=bit;}}if(mask)s.put(x+cx,y+cy,String.fromCodePoint(0x2800+mask),{fg:active?color:P.line});} if(n===null)txt(s,x+Math.floor((w-7)/2),y+Math.floor(h/2),'unknown',7,P.dim);else{const v=String(Math.round(n)),bw=v.length*4-1;big(s,x+Math.floor((w-bw-1)/2),y+2,v,P.white,w);txt(s,x+Math.floor((w-bw-1)/2)+bw+1,y+4,'%',1,P.dim);} }
export function trend(s:Screen,x:number,y:number,w:number,h:number,data:{x:number;y:number}[],color:RGB,xmin?:number,xmax?:number) { const valid=data.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)).sort((a,b)=>a.x-b.x);if(!valid.length)return;const lo=xmin??Math.min(...valid.map(p=>p.x)),hi=xmax??Math.max(...valid.map(p=>p.x));const mask=new Map<number,number>();const dot=(px:number,py:number)=>{const cx=Math.floor(px/2),cy=Math.floor(py/4);if(cx<0||cx>=w||cy<0||cy>=h)return;const k=cy*w+cx;mask.set(k,(mask.get(k)??0)|bits[py%4][px%2]);};let prev:{x:number;y:number}|null=null;for(const p of valid){const cur={x:Math.round((p.x-lo)/(hi-lo||1)*(w*2-1)),y:Math.round((1-(pct(p.y)??0)/100)*(h*4-1))};if(prev){const steps=Math.max(Math.abs(cur.x-prev.x),Math.abs(cur.y-prev.y),1);for(let j=0;j<=steps;j++)dot(Math.round(prev.x+(cur.x-prev.x)*j/steps),Math.round(prev.y+(cur.y-prev.y)*j/steps));}else dot(cur.x,cur.y);prev=cur;}for(const [k,v] of mask)s.put(x+k%w,y+Math.floor(k/w),String.fromCodePoint(0x2800+v),{fg:color}); }
export function age(at:string|null,now:number):string {const time=Date.parse(at??'');if(!Number.isFinite(time))return 'time unknown';const mins=Math.max(0,Math.floor((now-time)/60000));return mins<60?`${mins}m ago`:mins<1440?`${Math.floor(mins/60)}h ago`:`${Math.floor(mins/1440)}d ago`;}
export function time(at:string|null):string {const n=Date.parse(at??'');return Number.isFinite(n)?new Date(n).toISOString().slice(11,16)+' UTC':'unknown';}

export function countdown(at:string|null,now:number):string {const n=Date.parse(at??'');if(!Number.isFinite(n))return 'unknown';const mins=Math.ceil((n-now)/60000);if(mins<=0)return 'due';return mins<60?`in ${mins}m`:`in ${Math.floor(mins/60)}h ${mins%60}m`;}
