import { Screen, type RGB } from '../term.ts';
import {providerName} from './wording.ts';
import type { Snapshot, ViewState, Hit, View, Step } from './types.ts';
import { P, safe, clip, txt, para, wrap, label, box, pct, statusColor, statusWord, bar, big, ring, trend, age, time, countdown } from './draw.ts';
export interface CommandItem { label:string; detail:string; view:View; id?:string; kind?:Hit['kind'] }
export function commandItems(snapshot:Snapshot,query:string):CommandItem[] {
  const all:CommandItem[]=[{label:'Fleet',detail:'All teams and decisions',view:'fleet'},...snapshot.teams.map(t=>({label:`Team ${t.name}`,detail:t.description,view:'team' as const,id:t.id,kind:'team' as const})),...snapshot.agents.map(a=>({label:`Agent ${a.name}`,detail:`${snapshot.teams.find(t=>t.id===a.teamId)?.name??a.teamId} · ${a.activity}`,view:'agent' as const,id:a.id,kind:'agent' as const})),...snapshot.tasks.map(t=>({label:`Task ${t.id}`,detail:t.title,view:'task' as const,id:t.id,kind:'task' as const})),...snapshot.prs.map(p=>({label:`PR #${p.number}`,detail:p.title,view:'pr' as const,id:p.id,kind:'pr' as const})),{label:'Capacity',detail:'Provider accounts and utilization',view:'capacity'}];
  const terms=safe(query).toLowerCase().trim().split(/\s+/).filter(Boolean);return all.filter(c=>terms.every(t=>safe(c.label+' '+c.detail).toLowerCase().includes(t)));
}
const choose=<T extends {id:string}>(list:T[],id:string|null,index:number):T|undefined=>id!==null?list.find(item=>item.id===id):list[Math.max(0,Math.min(list.length-1,index))];
const agentMark=(a:Snapshot['agents'][number],frame:number)=>a.status==='ok'&&/\b(working|reviewing|implementing|checking|running|building|writing|testing|editing|reading)\b/i.test(a.activity.split(' · ' ,1)[0])?['⠋','⠙','⠹','⠸'][frame%4]:'●';
const value=(n:number|null|undefined)=>n==null||!Number.isFinite(n)?'unknown':`${Math.round(n)}%`;

/** Compare like usage windows; unknown accounts do not erase observed samples. */
function providerSummaries(snapshot:Snapshot) {
  return [...new Set(snapshot.capacity.map(c=>c.provider))].map(provider=>{
    const accounts=snapshot.capacity.filter(c=>c.provider===provider);
    const short=accounts.filter(c=>pct(c.used)!==null),weekly=accounts.filter(c=>pct(c.weekly)!==null);
    const window=short.length?'5h':weekly.length?'weekly':null;
    const known=window==='5h'?short:weekly;
    const used=known.length?known.reduce((sum,c)=>sum+((window==='5h'?c.used:c.weekly)??0),0)/known.length:null;
    const dates=(values:(string|null|undefined)[])=>values.filter((at):at is string=>!!at&&Number.isFinite(Date.parse(at))).sort((a,b)=>Date.parse(a)-Date.parse(b));
    const resetAt=dates(accounts.map(c=>c.resetAt))[0]??null;
    const cooldownUntil=dates(accounts.map(c=>c.cooldownUntil))[0]??null;
    const creditAccounts=accounts.filter(c=>c.credits);
    const creditValues=[...new Set(creditAccounts.map(c=>c.credits!))];
    const credits=creditAccounts.length===1?creditAccounts[0].credits:creditValues.length===1&&!/[\d$€£]/.test(creditValues[0])?`${creditValues[0]} (${creditAccounts.length} accounts)`:creditAccounts.map(c=>`${c.label}: ${c.credits}`).join(' · ');
    const status=accounts.some(c=>c.status==='blocked')?'blocked':accounts.some(c=>c.status==='waiting')?'waiting':accounts.every(c=>c.status==='ok')?'ok':'unknown';
    return {provider,accounts,used,window,known:known.length,resetAt,cooldownUntil,credits,status};
  });
}
function capacityTiming(c:{resetAt:string|null;cooldownUntil?:string|null},at:number):string {
  const reset=c.resetAt?countdown(c.resetAt,at):null,cooldown=c.cooldownUntil?countdown(c.cooldownUntil,at):null;
  return [reset?(reset==='due'?'reset due':`resets ${reset}`):'',cooldown?(cooldown==='due'?'cooldown end due':`cooldown ends ${cooldown}`):''].filter(Boolean).join(' · ')||'Reset time not reported';
}

function usageText(c:ReturnType<typeof providerSummaries>[number],width:number):string {
  if(!c.window)return 'Usage not reported';
  const long=`${value(c.used)} of ${c.window==='5h'?'5-hour':'weekly'} limit used`;
  const text=long.length<=width?long:`${value(c.used)} of ${c.window} limit used`;
  return c.known>1&&text.length+11<=width?text+' on average':text;
}
function observedText(c:ReturnType<typeof providerSummaries>[number]):string {return `Observed ${c.known} of ${c.accounts.length} ${c.accounts.length===1?'account':'accounts'}`;}

export function renderV3(snapshot:Snapshot,w:number,h:number,state:ViewState):{screen:Screen;hits:Hit[]} {
  const screen=new Screen(w,h,P.bg),s=screen,hits:Hit[]=[];
  const hit=(x:number,y:number,width:number,height:number,view:View,id?:string,kind?:Hit['kind'])=>{const xx=Math.max(0,x),yy=Math.max(0,y),ww=Math.min(w,x+width)-xx,hh=Math.min(h-1,y+height)-yy;if(ww>0&&hh>0)hits.push({x:xx,y:yy,w:ww,h:hh,view,...(id?{id}:{}),...(kind?{kind}:{})});};
  if(w<100||h<30){txt(s,2,2,'Resize terminal to at least 100 × 30.',w-4,P.white);return {screen,hits};}
  const compact=h<42, end=h-3, name=(id:string|null)=>snapshot.teams.find(t=>t.id===id)?.name??'Unknown team';
  const title=(word:string,detail:string,sub:string,color:RGB=P.dim)=>{const size=Math.min(Math.floor(w*.48),word.length*4-1);big(s,2,2,word,P.white,size);const x=Math.min(w-35,size+6);txt(s,x,2,detail,w-x-2,P.white,true);txt(s,x,3,sub,w-x-2,color);};
  const history=(x:number,y:number,width:number,height:number,steps:Step[])=>{
    if(!steps.length){txt(s,x,y,'History not recorded',width,P.dim);return;}
    const rows=steps.flatMap(step=>[
      ...wrap(`${step.state==='done'?'✓':'●'} ${step.label}`,width).map(text=>({text,color:statusColor(step.state)})),
      ...wrap(`${step.at?time(step.at):'time unknown'} · ${step.detail||step.state}`,width-2).map(text=>({text:'  '+text,color:P.dim})),
    ]);
    const start=Math.min(Math.max(0,state.scroll),Math.max(0,rows.length-height));
    rows.slice(start,start+Math.max(0,height)).forEach((row,i)=>txt(s,x,y+i,row.text,width,row.color));
  };
  const journey=(x:number,y:number,width:number,steps:Step[])=>{if(!steps.length){txt(s,x,y,'Journey not recorded',width,P.dim);return;}const count=Math.min(steps.length,Math.max(1,Math.floor(width/9))),cw=Math.floor(width/count);steps.slice(0,count).forEach((step,i)=>{const xx=x+i*cw;txt(s,xx,y-1,step.label,cw-1,statusColor(step.state));txt(s,xx,y,(step.state==='done'?'●':step.state==='active'?(state.frame%2?'●':'◉'):'○')+(i<count-1?'─'.repeat(cw-1):''),cw,statusColor(step.state));txt(s,xx,y+1,step.at?time(step.at):step.state,cw-1,P.dim);});};
  const recent=(x:number,y:number,width:number,height:number,teamId?:string)=>{const events=snapshot.events.filter(e=>!teamId||e.teamId===teamId).slice(0,Math.max(1,Math.floor(height/2)));if(!events.length)txt(s,x,y,'No recent events recorded',width,P.dim);events.forEach((event,i)=>{txt(s,x,y+i*2,`${time(event.at)}  ${event.text}`,width,statusColor(event.status));if(event.taskId)hit(x,y+i*2,width,1,'task',event.taskId,'task');});};
  const selectedTeam=choose(snapshot.teams,state.view==='fleet'?null:state.teamId,state.selected);
  function fleet(){
    txt(s,2,2,snapshot.headline||'Fleet status unknown',w-4,P.white,true);
    txt(s,2,3,`${snapshot.teams.length} teams   ${snapshot.agents.length} agents   ${snapshot.tasks.length} tasks   ${snapshot.prs.length} pull requests`,w-4,P.dim);
    label(s,2,5,w-4,'NEEDS YOU',`${snapshot.decisions.length} decisions`);
    const decisions=snapshot.decisions.slice(0,3);
    if(!decisions.length){
      if(snapshot.lastDecision){txt(s,2,6,`Last answered · ${age(snapshot.lastDecision.answeredAt,snapshot.at)}`,w-4,P.dim);txt(s,2,7,snapshot.lastDecision.question,w-4,P.fg);if(snapshot.lastDecision.answer)txt(s,2,8,snapshot.lastDecision.answer,w-4,P.dim);}
      else txt(s,2,6,'No decisions need you · last answer not recorded',w-4,P.dim);
    }
    decisions.forEach((d,i)=>{const teamWidth=Math.min(20,Math.floor(w*.13)),rightWidth=12;txt(s,2,6+i,'●',2,P.red);txt(s,5,6+i,name(d.teamId),teamWidth,P.white);txt(s,6+teamWidth,6+i,d.question+(d.blocks?` · ${d.blocks}`:''),w-teamWidth-rightWidth-9,P.fg);txt(s,w-rightWidth-2,6+i,age(d.createdAt,snapshot.at),rightWidth,P.dim);hit(2,6+i,w-4,1,'task',d.id,'decision');});
    label(s,2,10,w-4,'PROJECTS');
    const count=Math.max(1,Math.min(snapshot.teams.length,Math.floor((w-3)/29))),cardWidth=Math.floor((w-3)/count),cardH=compact?Math.max(11,h-20):23,bottom=11+cardH+1;
    let start=0;const selectedIndex=snapshot.teams.findIndex(t=>t.id===selectedTeam?.id);if(selectedIndex>=count)start=selectedIndex-count+1;
    const visible=snapshot.teams.slice(start,start+count);
    if(!visible.length)txt(s,2,12,'No teams available',w-4,P.dim);
    visible.forEach((t,i)=>{const x=2+i*cardWidth,cw=cardWidth-1,sel=t.id===selectedTeam?.id,c=statusColor(t.status);box(s,x,11,cw,cardH,sel?P.blue:P.line,sel?P.select:P.bg);txt(s,x+2,12,t.name,cw-4,P.white,true);txt(s,x+2,13,t.description,cw-4,P.dim);
      if(!compact){const rx=x+Math.floor((cw-16)/2);ring(s,rx,15,t.kind==='operations'?null:t.progress,c);if(t.kind==='operations'){txt(s,rx+4,19,'        ',8);big(s,rx+2,17,'OPS',c,12);}if(t.progressLabel&&t.kind!=='operations')txt(s,x+2,23,t.progressLabel,cw-4,P.dim);txt(s,x+2,24,t.kind==='operations'?'Operational status':t.milestone??'Milestone unknown',cw-4,P.white);txt(s,x+2,25,t.kind==='operations'?statusWord(t.status):`ETA ${t.eta ? (Number.isFinite(Date.parse(t.eta)) ? time(t.eta) : t.eta) : 'unknown'}`,cw-4,P.dim);para(s,x+2,27,cw-4,3,t.sentence||'Status unavailable');txt(s,x+2,31,`● ${statusWord(t.status)}${t.reason?' · '+t.reason:''}`,cw-4,c);txt(s,x+2,32,`${t.agentIds.length} agents · ${t.taskIds.length} tasks`,cw-4,P.dim);}
      else{txt(s,x+2,15,t.kind==='operations'?`Operations · ${statusWord(t.status)}`:`${value(t.progress)} · ${t.milestone??'milestone unknown'}`,cw-4,P.white);bar(s,x+2,16,cw-4,t.progress,c);para(s,x+2,18,cw-4,Math.max(1,cardH-9),t.sentence||'Status unavailable');txt(s,x+2,11+cardH-2,`● ${statusWord(t.status)}`,cw-4,c);}hit(x,11,cw,cardH,'team',t.id,'team');});
    const split=Math.floor(w*.47);label(s,2,bottom,split-4,'CAPACITY');label(s,split,bottom,w-split-2,'JUST HAPPENED');
    const available=end-bottom;if(!snapshot.capacity.length)txt(s,2,bottom+2,'Capacity unavailable',split-4,P.dim);
    providerSummaries(snapshot).slice(0,Math.min(4,Math.max(1,Math.floor(available/2)))).forEach((c,i)=>{
      const y=bottom+2+i*2,barWidth=Math.max(5,Math.floor((split-20)*.35)),textX=16+barWidth;
      txt(s,2,y,providerName(c.provider),10,P.fg);bar(s,14,y,barWidth,c.used,statusColor(c.status));
      txt(s,textX,y,usageText(c,split-textX-2),split-textX-2,P.fg);
      txt(s,2,y+1,[observedText(c),c.credits?(/credits/i.test(c.credits)?c.credits:`Credits: ${c.credits}`):'',capacityTiming(c,snapshot.at)].filter(Boolean).join(' · '),split-4,P.dim);
    });recent(split,bottom+2,w-split-2,available);
  }
  function team(){const t=selectedTeam;if(!t){txt(s,2,3,'No teams available',w-4,P.dim);return;}title(t.name,t.description,`${statusWord(t.status)} · ${t.sentence}`,statusColor(t.status));if(t.progressLabel)txt(s,2,5,t.progressLabel,w-4,P.dim);label(s,2,7,w-4,'MILESTONES');journey(2,10,w-4,t.milestones);
    const split=Math.floor(w*.65),bottom=compact?h-8:Math.min(36,h-13);label(s,2,14,split-5,'FEATURE JOURNEYS');label(s,split,14,w-split-2,'AGENTS');
    const agents=snapshot.agents.filter(a=>a.teamId===t.id),tasks=snapshot.tasks.filter(a=>a.teamId===t.id),rows=Math.max(1,Math.floor((bottom-16)/3)),arows=Math.max(1,Math.floor((bottom-16)/2)),taskIndex=Math.max(0,state.selected-agents.length),taskStart=state.selected>=agents.length?Math.max(0,taskIndex-rows+1):0,agentStart=state.selected<agents.length?Math.max(0,state.selected-arows+1):0;
    if(!tasks.length)txt(s,2,16,'No feature journeys recorded',split-5,P.dim);tasks.slice(taskStart,taskStart+rows).forEach((task,i)=>{const y=16+i*3,selected=state.selected===agents.length+taskStart+i;if(selected)s.shade(2,y,split-5,P.select);txt(s,3,y,task.title,split-7,selected?P.blue:P.fg,true);const dots=task.steps.length?task.steps.map(st=>(st.state==='done'?'●':st.state==='active'?'◉':'○')+' '+st.label).join('  '):'Journey not recorded';txt(s,3,y+1,dots,split-7,P.dim);hit(2,y,split-5,2,'task',task.id,'task');});
    if(!agents.length)txt(s,split,16,'No agents available',w-split-2,P.dim);agents.slice(agentStart,agentStart+arows).forEach((a,i)=>{const y=16+i*2,selected=state.selected===agentStart+i;if(selected)s.shade(split,y,w-split-2,P.select);txt(s,split,y,`${agentMark(a,state.frame)} ${a.name}`,Math.floor((w-split)*.48),selected?P.blue:statusColor(a.status),true);txt(s,split+Math.floor((w-split)*.48),y,`${a.model??'model unknown'} ${value(a.context)}`,Math.floor((w-split)*.52)-2,P.dim);txt(s,split+2,y+1,a.activity,w-split-4,P.dim);hit(split,y,w-split-2,2,'agent',a.id,'agent');});
    label(s,2,bottom,split-5,'MERGED PER DAY');if(snapshot.sources[`merges:${t.id}`])txt(s,2,bottom+1,snapshot.sources[`merges:${t.id}`],split-5,P.dim);label(s,split,bottom,w-split-2,'RECENT');const chartH=Math.max(2,end-bottom-2);if(!t.merges?.length)txt(s,2,bottom+2,'Merge history unavailable',split-5,P.dim);else{const values=t.merges.slice(-Math.max(1,Math.floor((split-8)/5))),max=Math.max(1,...values.map(v=>v.count)),step=Math.max(4,Math.floor((split-8)/values.length));txt(s,2,bottom+2,String(max),3,P.dim);for(let i=0;i<values.length;i++){const xx=6+i*step,n=Math.round(values[i].count/max*Math.max(1,chartH-2));for(let j=0;j<n;j++)txt(s,xx,bottom+chartH-j,'██',2,P.blue);txt(s,xx,bottom+chartH+1,(/^\d{4}-\d{2}-\d{2}/.test(values[i].day)?values[i].day.slice(8,10):values[i].day),step-1,P.dim);} }recent(split,bottom+2,w-split-2,end-bottom-1,t.id);
  }
  function agent(){const list=state.agentId!==null||state.teamId===null?snapshot.agents:snapshot.agents.filter(a=>a.teamId===state.teamId);const a=choose(list,state.agentId,state.selected);if(!a){txt(s,2,3,'No agents available',w-4,P.dim);return;}title(a.name,`${name(a.teamId)} · ${a.model??'model unknown'}`,`${agentMark(a,state.frame)} ${statusWord(a.status)} · ${a.activity}`,statusColor(a.status));const split=Math.floor(w*.65);box(s,2,7,split-5,h-10);txt(s,4,7,' LIVE TERMINAL ',split-9,P.dim,true);txt(s,4,8,a.tailAt?`Captured ${age(new Date(a.tailAt).toISOString(),snapshot.at)}`:'Capture time unknown',split-9,P.dim);
    if(a.tail===null)txt(s,4,10,'Terminal tail unavailable',split-9,P.dim);else{const lines=a.tail.split('\n'),height=h-14,start=Math.max(0,lines.length-height-Math.max(0,state.scroll));lines.slice(start,start+height).forEach((line,i)=>txt(s,4,10+i,line,split-9));}
    label(s,split,7,w-split-2,'CONTEXT');if(!compact){ring(s,split,8,a.context,statusColor(a.status));txt(s,split+18,10,`${value(a.context)} context`,w-split-20,P.white);txt(s,split+18,12,'Recorded usage',w-split-20,P.dim);if(a.contextHistory.length)trend(s,split+18,14,w-split-21,3,a.contextHistory.map((v,i)=>({x:i,y:v})),P.blue);else txt(s,split+18,14,'History unavailable',w-split-20,P.dim);}else{txt(s,split,9,`${value(a.context)} context`,w-split-2,P.white);bar(s,split,10,w-split-2,a.context,P.blue);}
    const nowY=compact?13:19,historyY=compact?20:29;label(s,split,nowY,w-split-2,'NOW');const task=snapshot.tasks.find(t=>t.id===a.taskId);if(task){para(s,split,nowY+2,w-split-2,2,task.title,P.white);txt(s,split,nowY+4,task.steps.length?task.steps.map(st=>(st.state==='done'?'●':'○')+' '+st.label).join('  '):'Journey not recorded',w-split-2,P.dim);hit(split,nowY+2,w-split-2,3,'task',task.id,'task');}else txt(s,split,nowY+2,'No current task recorded',w-split-2,P.dim);label(s,split,historyY,w-split-2,'HISTORY');history(split,historyY+2,w-split-2,end-historyY-1,a.history);
  }
  function task(){const boundTask=state.agentId!==null?snapshot.agents.find(a=>a.id===state.agentId)?.taskId:null;const list=state.taskId!==null?snapshot.tasks:state.agentId!==null?snapshot.tasks.filter(t=>t.id===boundTask):state.teamId!==null?snapshot.tasks.filter(t=>t.teamId===state.teamId):snapshot.tasks;const t=choose(list,state.taskId,state.selected);if(!t){txt(s,2,3,'No tasks available',w-4,P.dim);return;}title(t.id,t.title,`${name(t.teamId)} · ${t.agentId??'owner unknown'} · ${age(t.createdAt,snapshot.at)}`);label(s,2,7,w-4,'JOURNEY');journey(2,10,w-4,t.steps);txt(s,2,13,'time spent',12,P.dim);
    const times=t.steps.map(st=>Date.parse(st.at??'')),durations=times.slice(1).map((n,i)=>n-times[i]);if(durations.length&&durations.every(n=>Number.isFinite(n)&&n>=0)&&durations.some(n=>n>0)){const total=durations.reduce((a,b)=>a+b,0),bw=Math.min(65,w-32);let x=15;durations.forEach((duration,i)=>{const width=Math.floor(bw*duration/total);bar(s,x,13,width,100,statusColor(t.steps[i].state));x+=width;});txt(s,16+bw,13,`${Math.round(total/60000)}m recorded`,w-18-bw,P.dim);}else txt(s,15,13,'unknown — timestamps not recorded',w-17,P.dim);
    const split=Math.floor(w*.62),doneY=compact?22:Math.min(32,h-10);label(s,2,16,split-5,'WHAT TO DO');para(s,2,18,split-5,doneY-19,t.body||t.title,P.fg,Math.max(0,state.scroll));label(s,2,doneY,split-5,'DONE WHEN');para(s,2,doneY+2,split-5,end-doneY-1,t.acceptance??'Acceptance criteria not recorded',P.fg,Math.max(0,state.scroll));
    label(s,split,16,w-split-2,'HISTORY');history(split,18,w-split-2,compact?4:10,t.steps);const py=compact?23:32;label(s,split,py,w-split-2,'LINKED PR');const pr=snapshot.prs.find(p=>p.id===t.prId);if(pr){txt(s,split,py+2,`#${pr.number}  ${pr.title}`,w-split-2,P.white,true);txt(s,split,py+3,`${pr.state} · ${pr.verdict}`,w-split-2,statusColor(pr.verdict));hit(split,py+2,w-split-2,2,'pr',pr.id,'pr');}else txt(s,split,py+2,'No linked PR recorded',w-split-2,P.dim);
  }
  function pr(){const linked=state.taskId!==null?snapshot.tasks.find(t=>t.id===state.taskId)?.prId:null;const list=state.prId!==null||state.taskId===null?snapshot.prs:snapshot.prs.filter(p=>p.id===linked);const p=choose(list,state.prId,state.selected),split=Math.floor(w*.3);label(s,2,2,split-5,'PULL REQUESTS');const count=Math.floor((h-7)/3),sel=snapshot.prs.findIndex(item=>item.id===p?.id),start=Math.max(0,sel-count+1);snapshot.prs.slice(start,start+count).forEach((item,i)=>{const y=4+i*3;if(item.id===p?.id){s.shade(2,y,split-5,P.select);s.shade(2,y+1,split-5,P.select);}txt(s,3,y,`#${item.number}  ${item.title}`,split-7,item.id===p?.id?P.blue:P.fg,true);txt(s,3,y+1,`${name(item.teamId)} · ${item.state} · ${item.freshness==='stale'||snapshot.stale?'STALE':item.verdict}`,split-7,P.dim);hit(2,y,split-5,2,'pr',item.id,'pr');});if(!p){txt(s,split,3,'No pull requests available',w-split-2,P.dim);return;}
    const stale=p.freshness==='stale'||snapshot.stale,verdict=stale?'UNKNOWN':p.verdict,historical=stale?(p.historicalGate??{verdict:p.verdict,reason:p.reason,observedAt:p.observedAt??null}):null;
    if(stale)txt(s,split,5,`STALE PR · last success ${p.observedAt?age(p.observedAt,snapshot.at):'unknown'} · ${p.refreshError??'cached data'}`,w-split-2,P.amber);
    const b=big(s,split,2,String(p.number),P.white,20);txt(s,split+b+4,2,p.title,w-split-b-6,P.white,true);txt(s,split+b+4,3,`${name(p.teamId)} · ${p.state}`,w-split-b-6,P.dim);txt(s,split+b+4,4,`+${p.additions??'?'}  −${p.deletions??'?'}  ${p.files??'?'} files`,w-split-b-6,P.dim);
    label(s,split,7,w-split-2,'PIPELINE');const aggregate=(steps:Step[])=>stale||!steps.length?'unknown' as const:steps.some(st=>st.state==='blocked')?'blocked' as const:steps.every(st=>st.state==='done')?'done' as const:'waiting' as const;journey(split,10,w-split-2,[{id:'checks',label:'Checks',state:aggregate(p.checks),at:null,detail:''},{id:'reviews',label:'Reviews',state:aggregate(p.reviews),at:null,detail:''},{id:'gate',label:'Gate',state:verdict==='ACT'?'done':verdict==='HOLD'?'blocked':verdict==='WAIT'?'waiting':'unknown',at:null,detail:''},{id:'merge',label:'Merged',state:!stale&&p.state.toLowerCase()==='merged'?'done':'unknown',at:null,detail:''}]);
    const gateH=compact?8:15;box(s,split,13,w-split-2,gateH,statusColor(verdict));txt(s,split+2,13,' JEV MERGE GATE ',w-split-6,P.dim,true);const bw=big(s,split+3,15,verdict,statusColor(verdict),w-split-8);if(!compact){txt(s,split+bw+7,16,stale?'Current gate unknown':p.band??'Band unknown',w-split-bw-11,P.dim);para(s,split+3,19,w-split-8,3,stale?'STALE · Current gate unknown':p.reason??'Gate evidence not recorded',P.white,Math.max(0,state.scroll));(stale?[]:p.signals).slice(Math.min(Math.max(0,state.scroll),Math.max(0,p.signals.length-3)),Math.min(Math.max(0,state.scroll),Math.max(0,p.signals.length-3))+3).forEach((signal,i)=>txt(s,split+3+i*Math.floor((w-split-8)/3),24,`${signal.name}  ${signal.value}`,Math.floor((w-split-8)/3)-1,P.dim));txt(s,split+3,26,`Recorded ${p.at?time(p.at):'time unknown'}`,w-split-8,P.dim);}else para(s,split+3,18,w-split-8,2,stale?'STALE · Current gate unknown':p.reason??'Gate evidence not recorded',P.fg,Math.max(0,state.scroll));
    if(historical){txt(s,split+3,compact?19:22,`Historical ${historical.verdict} · ${historical.observedAt?time(historical.observedAt):'observation unknown'}`,w-split-8,P.amber);if(!compact)para(s,split+3,23,w-split-8,2,historical.reason??'Prior reason not recorded',P.dim,Math.max(0,state.scroll));}
    const y=compact?22:30,half=Math.floor((w-split-4)/2);label(s,split,y,half,stale?'CHECKS · historical':'CHECKS');label(s,split+half+2,y,w-split-half-4,stale?'REVIEWS · historical':'REVIEWS');history(split,y+2,half,end-y-1,p.checks);history(split+half+2,y+2,w-split-half-4,end-y-1,p.reviews);
  }
  function capacity(){
    const summaries=providerSummaries(snapshot),providers=summaries.map(c=>c.provider),count=Math.max(1,Math.min(4,providers.length)),cw=Math.floor((w-4)/count);
    if(!providers.length)txt(s,2,3,'Capacity unavailable',w-4,P.dim);
    summaries.slice(0,count).forEach((c,i)=>{
      const x=2+i*cw;txt(s,x,2,providerName(c.provider),cw-2,P.white,true);txt(s,x,3,observedText(c),cw-2,P.dim);if(c.credits)para(s,x+12,4,cw-14,2,/credits/i.test(c.credits)?c.credits:`Credits: ${c.credits}`,P.dim);
      big(s,x,4,c.used===null?'--':String(Math.round(c.used)),P.white,cw-4);txt(s,x+12,6,c.window?'% used':'unknown',cw-14,P.dim);
      txt(s,x,7,usageText(c,cw-2),cw-2,P.dim);bar(s,x,8,cw-3,c.used,P.dim);txt(s,x,9,capacityTiming(c,snapshot.at),cw-2,P.dim);
    });
    const chartY=12,chartH=compact?6:14,bottom=compact?21:30;label(s,2,11,w-4,'UTILIZATION (%)','recorded samples');const colors:RGB[]=[P.blue,P.amber,P.green,[174,145,215]];const samples=snapshot.capacity.flatMap(c=>c.history).filter(p=>Number.isFinite(p.at)&&Number.isFinite(p.used)),lo=Math.min(...samples.map(p=>p.at)),hi=Math.max(...samples.map(p=>p.at));txt(s,2,chartY,'100',4,P.dim);txt(s,2,chartY+chartH-1,'0',4,P.dim);for(let j=0;j<chartH;j++)txt(s,6,chartY+j,'│',1,P.line);txt(s,6,chartY+chartH,'└'+'─'.repeat(w-10),w-8,P.line);if(!samples.length)txt(s,9,chartY+2,'Utilization history unavailable',w-12,P.dim);else{snapshot.capacity.forEach(c=>{for(const window of ['5h','weekly'])trend(s,8,chartY,w-12,chartH,c.history.filter(p=>(p.window??'5h')===window).map(p=>({x:p.at,y:p.used})),colors[providers.indexOf(c.provider)%colors.length],lo,hi);});txt(s,8,chartY+chartH+1,time(new Date(lo).toISOString()),15,P.dim);txt(s,w-19,chartY+chartH+1,time(new Date(hi).toISOString()),15,P.dim);}
    providers.slice(0,4).forEach((provider,i)=>txt(s,8+i*Math.floor((w-16)/4),chartY+chartH+2,'━ '+providerName(provider)+' '+[...new Set(snapshot.capacity.filter(c=>c.provider===provider).flatMap(c=>c.history.map(p=>p.window??'5h')))].join('/'),Math.floor((w-16)/4)-1,colors[i%colors.length]));
    const split=Math.floor(w*.65);label(s,2,bottom,split-5,'ACCOUNTS');label(s,split,bottom,w-split-2,'FALLBACK');txt(s,2,bottom+1,'ACCOUNT                  5H      WEEKLY    RESET / COOLDOWN / CREDITS',split-5,P.dim);const rows=Math.max(1,Math.floor((end-bottom-1)/2));snapshot.capacity.slice(Math.max(0,state.scroll),Math.max(0,state.scroll)+rows).forEach((c,i)=>{const y=bottom+3+i*2;txt(s,2,y,c.label,24,P.fg);txt(s,27,y,value(c.used),8,statusColor(c.status));txt(s,35,y,value(c.weekly),10,P.dim);txt(s,45,y,c.credits??capacityTiming(c,snapshot.at),split-47,P.dim);});
    const fallback=snapshot.events.filter(e=>/fallback|rerout|429|cooldown/i.test(e.text));para(s,split,bottom+2,w-split-2,compact?1:4,fallback.length?fallback.map(e=>e.text).join('\n'):'No fallback events recorded',P.dim);const resetY=compact?bottom+4:bottom+7;label(s,split,resetY,w-split-2,'RESETS / COOLDOWNS');para(s,split,resetY+2,w-split-2,Math.max(1,end-resetY-1),snapshot.capacity.length?snapshot.capacity.map(c=>`${c.label}: ${capacityTiming(c,snapshot.at)}${c.reason&&!c.cooldownUntil?' · '+c.reason:''}`).join('\n'):'Reset times unknown',P.dim);
  }
  ({fleet,team,agent,task,pr,capacity}[state.view])();
  txt(s,2,0,'◆',1,P.blue,true);txt(s,4,0,'rig console',12,P.white,true);let tabX=20;(['fleet','team','agent','task','pr','capacity'] as View[]).forEach((view,i)=>{const text=`${i+1} ${view==='pr'?'PR':view[0].toUpperCase()+view.slice(1)}`;txt(s,tabX,0,text,text.length,state.view===view?P.blue:P.dim,state.view===view);hit(tabX,0,text.length,1,view);tabX+=text.length+3;});const feed=state.paused?'paused':snapshot.stale?'stale':'live';txt(s,w-18,0,`${feed}  ${time(new Date(snapshot.at).toISOString())}`,17,snapshot.stale?P.amber:P.dim);
  txt(s,2,h-1,'↵ open   esc back   1–6 views   ←→ / j k select   ? help   : command',w-4,P.dim);if(w>=140)txt(s,w-45,h-1,`${clip(snapshot.source,31)} · read-only`,43,P.dim);if(['agent','task','pr','capacity'].includes(state.view))txt(s,2,h-2,'[ ] detail line · PgUp / PgDn page',w-4,P.dim);const degraded=Object.entries(snapshot.sources).filter(([k,v])=>/^(daemon|accounts|github|progress|details|transitions)(:|$)/.test(k)&&/unavailable|stale|cached|error|failed/i.test(v)).map(([k,v])=>`${k}: ${v}`).join(' · ');if(state.note||degraded)txt(s,2,h-2,state.note??degraded,w-4,P.amber);
  if(state.help||state.command!==null){for(const cell of s.cells){cell.dim=true;cell.fg=P.line;}hits.length=0;const bw=Math.min(80,w-8),x=Math.floor((w-bw)/2);
    if(state.help){const bh=Math.min(30,h-4),y=Math.floor((h-bh)/2);box(s,x,y,bw,bh,P.blue);txt(s,x+2,y,' Help ',bw-4,P.white,true);const rows=[['1 – 6','Fleet · Team · Agent · Task · PR · Capacity'],['↵','open the selected item'],['esc','go back one level'],['← → / j k','move the selection'],['click','open a card, agent, task, PR or decision'],[':','command palette'],['p','pause snapshot updates'],['r','refresh data'],['[ ] / PgUp PgDn','detail line / page'],['q','quit'],['● green','on track'],['● amber','waiting'],['● red','blocked, or needs you'],['ring','recorded milestone progress']];rows.slice(0,bh-5).forEach(([key,detail],i)=>{txt(s,x+3,y+2+i,key,17,P.blue);txt(s,x+22,y+2+i,detail,bw-25,P.fg);});txt(s,x+3,y+bh-3,'read-only · unknown values stay unknown',bw-6,P.dim);txt(s,x+3,y+bh-2,'? / esc close',bw-6,P.dim);}
    else{const bh=Math.min(20,h-6),y=Math.min(6,h-bh-2);box(s,x,y,bw,bh,P.blue);txt(s,x+2,y+1,'❯ '+state.command+'▏',bw-4,P.white);label(s,x+2,y+3,bw-4,'COMMAND');const items=commandItems(snapshot,state.command??''),visible=bh-7,selection=Math.max(0,Math.min(items.length-1,state.selected)),start=Math.max(0,selection-visible+1);items.slice(start,start+visible).forEach((item,i)=>{const yy=y+5+i;if(start+i===selection)s.shade(x+1,yy,bw-2,P.select);txt(s,x+3,yy,item.label,Math.floor(bw*.45),start+i===selection?P.blue:P.fg);txt(s,x+Math.floor(bw*.47),yy,item.detail,Math.floor(bw*.5)-2,P.dim);hit(x+1,yy,bw-2,1,item.view,item.id,item.kind);});if(!items.length)txt(s,x+3,y+5,'No matching commands',bw-6,P.dim);txt(s,x+3,y+bh-2,'↑ ↓ select    ↵ open    esc close',bw-6,P.dim);}
  }
  return {screen,hits};
}
